from django.urls import path

from .web import dashboard as dashboard_views
from .web import library as library_views
from .web import detail as detail_views
from .web import igdb as igdb_views
from .web import platinum as platinum_views
from .web import franchise as franchise_views

app_name = "games"


urlpatterns = [
    path(
        "",
        dashboard_views.dashboard,
        name="dashboard",
    ),
    path(
        "library/",
        library_views.library,
        name="library",
    ),
    path(
        "platinum/",
        platinum_views.platinum,
        name="platinum",
    ),
    path(
        "franchises/",
        franchise_views.franchise_list,
        name="franchise_list",
    ),
    path(
        "franchises/create/",
        franchise_views.create_franchise,
        name="create_franchise",
    ),
    path(
        "franchises/<slug:slug>/update/",
        franchise_views.update_franchise,
        name="update_franchise",
    ),
    path(
        "franchises/<slug:slug>/delete/",
        franchise_views.delete_franchise,
        name="delete_franchise",
    ),
    path(
        "franchises/<slug:slug>/",
        franchise_views.franchise_detail,
        name="franchise_detail",
    ),
    path(
        (
            "library/<slug:slug>/"
            "franchise/update/"
        ),
        detail_views.update_game_franchise,
        name="update_game_franchise",
    ),
    path(
        "igdb/search/",
        igdb_views.igdb_search,
        name="igdb_search",
    ),
    path(
        "igdb/<int:igdb_id>/import/",
        igdb_views.igdb_import,
        name="igdb_import",
    ),
    path(
        "library/<slug:slug>/",
        detail_views.detail,
        name="detail",
    ),
    path(
        "library/<slug:slug>/update/",
        detail_views.update_entry,
        name="update_entry",
    ),
    path(
        (
            "library/<slug:slug>/"
            "playthroughs/<int:playthrough_id>/action/"
        ),
        detail_views.update_playthrough_state,
        name="update_playthrough_state",
    ),
    path(
        "library/<slug:slug>/igdb/refresh/",
        igdb_views.igdb_refresh,
        name="igdb_refresh",
    ),
    path(
        (
            "library/<slug:slug>/"
            "playthroughs/<int:playthrough_id>/update/"
        ),
        detail_views.update_playthrough,
        name="update_playthrough",
    ),
    path(
        (
            "library/<slug:slug>/"
            "playthroughs/<int:playthrough_id>/delete/"
        ),
        detail_views.delete_playthrough,
        name="delete_playthrough",
    ),
    path(
        (
            "library/<slug:slug>/"
            "playthroughs/create/"
        ),
        detail_views.create_playthrough,
        name="create_playthrough",
    ),
    path(
        (
            "library/<slug:slug>/"
            "accesses/create/"
        ),
        detail_views.create_access,
        name="create_access",
    ),
    path(
        (
            "library/<slug:slug>/"
            "accesses/<int:access_id>/update/"
        ),
        detail_views.update_access,
        name="update_access",
    ),
    path(
        (
            "library/<slug:slug>/"
            "accesses/<int:access_id>/delete/"
        ),
        detail_views.delete_access,
        name="delete_access",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/create/"
        ),
        detail_views.create_manual_content,
        name="create_manual_content",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/igdb/"
            "<int:igdb_content_id>/track/"
        ),
        detail_views.track_igdb_content,
        name="track_igdb_content",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/<int:content_id>/update/"
        ),
        detail_views.update_content,
        name="update_content",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/<int:content_id>/delete/"
        ),
        detail_views.delete_content,
        name="delete_content",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/modes/create/"
        ),
        detail_views.create_competitive_mode,
        name="create_competitive_mode",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/tiers/create/"
        ),
        detail_views.create_competitive_tier,
        name="create_competitive_tier",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/records/create/"
        ),
        detail_views.create_competitive_record,
        name="create_competitive_record",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/records/"
            "<int:record_id>/update/"
        ),
        detail_views.update_competitive_record,
        name="update_competitive_record",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/records/"
            "<int:record_id>/delete/"
        ),
        detail_views.delete_competitive_record,
        name="delete_competitive_record",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/modes/"
            "<int:mode_id>/update/"
        ),
        detail_views.update_competitive_mode,
        name="update_competitive_mode",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/modes/"
            "<int:mode_id>/delete/"
        ),
        detail_views.delete_competitive_mode,
        name="delete_competitive_mode",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/tiers/"
            "<int:tier_id>/update/"
        ),
        detail_views.update_competitive_tier,
        name="update_competitive_tier",
    ),
    path(
        (
            "library/<slug:slug>/"
            "competitive/tiers/"
            "<int:tier_id>/delete/"
        ),
        detail_views.delete_competitive_tier,
        name="delete_competitive_tier",
    ),
]