from django.urls import path

from .web import dashboard as dashboard_views
from .web import library as library_views
from .web import detail as detail_views
from .web import igdb as igdb_views

app_name = "games"


urlpatterns = [
    path(
        "",
        dashboard_views.dashboard,
        name="dashboard",
    ),
    path(
        "library/",
        library_views.library,
        name="library",
    ),
    path(
        "igdb/search/",
        igdb_views.igdb_search,
        name="igdb_search",
    ),
        path(
        "igdb/<int:igdb_id>/import/",
        igdb_views.igdb_import,
        name="igdb_import",
    ),
    path(
        "library/<slug:slug>/",
        detail_views.detail,
        name="detail",
    ),
    path(
        "library/<slug:slug>/update/",
        detail_views.update_entry,
        name="update_entry",
    ),
    path(
        (
            "library/<slug:slug>/"
            "playthroughs/<int:playthrough_id>/action/"
        ),
        detail_views.update_playthrough_state,
        name="update_playthrough_state",
    ),
        path(
        "library/<slug:slug>/igdb/refresh/",
        igdb_views.igdb_refresh,
        name="igdb_refresh",
    ),
    path(
        (
            "library/<slug:slug>/"
            "playthroughs/<int:playthrough_id>/update/"
        ),
        detail_views.update_playthrough,
        name="update_playthrough",
    ),
    path(
        (
            "library/<slug:slug>/"
            "playthroughs/create/"
        ),
        detail_views.create_playthrough,
        name="create_playthrough",
    ),
    path(
        (
            "library/<slug:slug>/"
            "accesses/create/"
        ),
        detail_views.create_access,
        name="create_access",
    ),
    path(
        (
            "library/<slug:slug>/"
            "accesses/<int:access_id>/update/"
        ),
        detail_views.update_access,
        name="update_access",
    ),
    path(
        (
            "library/<slug:slug>/"
            "accesses/<int:access_id>/delete/"
        ),
        detail_views.delete_access,
        name="delete_access",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/create/"
        ),
        detail_views.create_manual_content,
        name="create_manual_content",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/igdb/"
            "<int:igdb_content_id>/track/"
        ),
        detail_views.track_igdb_content,
        name="track_igdb_content",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/<int:content_id>/update/"
        ),
        detail_views.update_content,
        name="update_content",
    ),
    path(
        (
            "library/<slug:slug>/"
            "content/<int:content_id>/delete/"
        ),
        detail_views.delete_content,
        name="delete_content",
    ),
]