# Generated by Django 6.0.7 on 2026-07-13 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('main_picture_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_status', models.CharField(blank=True, max_length=50, null=True)),
                ('num_volumes', models.PositiveIntegerField(default=0)),
                ('num_chapters', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('list_status', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField(default=0)),
                ('num_volumes_read', models.PositiveIntegerField(default=0)),
                ('num_chapters_read', models.PositiveIntegerField(default=0)),
                ('is_rereading', models.BooleanField(default=False)),
                ('updated_at_mal', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-updated_at_mal', 'title'],
            },
        ),
    ]
