# Generated by Django 6.0.7 on 2026-07-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0003_animerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeentry',
            name='title_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animeentry',
            name='title_japanese',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
