# Generated by Django 6.0.7 on 2026-07-16 00:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0005_animesyncevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeAiringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('anilist_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title_romaji', models.CharField(blank=True, max_length=255, null=True)),
                ('title_english', models.CharField(blank=True, max_length=255, null=True)),
                ('title_native', models.CharField(blank=True, max_length=255, null=True)),
                ('anilist_status', models.CharField(blank=True, max_length=50, null=True)),
                ('anilist_episodes', models.PositiveIntegerField(default=0)),
                ('next_airing_episode', models.PositiveIntegerField(blank=True, null=True)),
                ('next_airing_at', models.DateTimeField(blank=True, null=True)),
                ('time_until_airing_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('episodes_aired_estimated', models.PositiveIntegerField(default=0)),
                ('streaming_links', models.JSONField(blank=True, default=list)),
                ('streaming_episodes', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airing_data', to='mal_data.animeentry')),
            ],
        ),
    ]
