# Generated by Django 6.0.7 on 2026-07-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0010_maloauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaentry',
            name='title_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mangaentry',
            name='title_japanese',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
