# Generated by Django 6.0.7 on 2026-07-27 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0011_mangaentry_title_english_mangaentry_title_japanese'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField()),
                ('title_snapshot', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('chapter_changed', 'Chapter changed'), ('volume_changed', 'Volume changed'), ('score_changed', 'Score changed')], max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='mal_data.mangaentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
