# Generated by Django 6.0.7 on 2026-07-27 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0012_mangasyncevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTrackedManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('title_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('dropped', 'Dropped'), ('plan_to_read', 'Plan to read')], max_length=50)),
                ('chapters_read', models.PositiveIntegerField(default=0)),
                ('volumes_read', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_rereading', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title_snapshot', 'mal_id'],
            },
        ),
    ]
