# Generated by Django 6.0.7 on 2026-07-27 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0013_manualtrackedmanga'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapterSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(unique=True)),
                ('canonical_total_chapters', models.PositiveIntegerField(default=0)),
                ('latest_available_chapter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('availability_source_type', models.CharField(choices=[('canonical', 'Canonical total'), ('external', 'External source'), ('manual', 'Manual')], default='canonical', max_length=30)),
                ('availability_source_name', models.CharField(blank=True, max_length=100)),
                ('availability_source_url', models.URLField(blank=True)),
                ('release_schedule', models.CharField(blank=True, max_length=100)),
                ('next_release_at', models.DateTimeField(blank=True, null=True)),
                ('external_checked_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_signal', to='mal_data.mangaentry')),
            ],
            options={
                'ordering': ['manga__title'],
            },
        ),
    ]
