# Generated by Django 6.0.7 on 2026-07-27 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0014_mangachaptersignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('source_title', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='mal_data.mangaentry')),
            ],
            options={
                'ordering': ['manga__title', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('manga', 'provider'), name='unique_manga_provider_source_link')],
            },
        ),
    ]
