# Generated by Django 6.0.7 on 2026-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0015_mangasourcelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangasourcelink',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mangasourcelink',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
