# Generated by Django 6.0.7 on 2026-08-18 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0016_mangasourcelink_is_official_mangasourcelink_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_mal_id', models.PositiveIntegerField()),
                ('source_title', models.CharField(max_length=255)),
                ('target_mal_id', models.PositiveIntegerField()),
                ('target_title', models.CharField(max_length=255)),
                ('target_media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_status', models.CharField(blank=True, max_length=50, null=True)),
                ('target_picture_url', models.URLField(blank=True, null=True)),
                ('target_num_episodes', models.PositiveIntegerField(default=0)),
                ('target_num_chapters', models.PositiveIntegerField(default=0)),
                ('target_num_volumes', models.PositiveIntegerField(default=0)),
                ('relation_type', models.CharField(max_length=100)),
                ('relation_type_formatted', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_source_type', models.CharField(max_length=20)),
                ('target_local_list_status', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='mal_data.mangaentry')),
            ],
            options={
                'ordering': ['source_title', 'relation_source_type', 'relation_type', 'target_title'],
                'constraints': [models.UniqueConstraint(fields=('source_mal_id', 'target_mal_id', 'relation_source_type', 'relation_type'), name='unique_manga_relation')],
            },
        ),
    ]
