# Generated by Django 6.0.7 on 2026-08-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0017_mangarelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animerelation',
            name='target_num_chapters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animerelation',
            name='target_num_episodes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animerelation',
            name='target_num_volumes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
