# Generated by Django 6.0.7 on 2026-08-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_data', '0018_animerelation_target_num_chapters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachaptersignal',
            name='latest_available_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
