# Generated by Django 6.0.7 on 2026-07-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameaccess',
            options={'ordering': ['platform_name', 'store']},
        ),
        migrations.RemoveConstraint(
            model_name='gameaccess',
            name='games_access_unique_location',
        ),
        migrations.AlterField(
            model_name='gameaccess',
            name='platform_name',
            field=models.CharField(choices=[('pc', 'PC'), ('ps5', 'PlayStation 5'), ('switch_2', 'Nintendo Switch 2'), ('other', 'Otra')], db_index=True, max_length=30, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='gameaccess',
            name='store',
            field=models.CharField(blank=True, choices=[('steam', 'Steam'), ('epic_games', 'Epic Games Store'), ('playstation_store', 'PlayStation Store'), ('nintendo_eshop', 'Nintendo eShop'), ('gog', 'GOG'), ('other', 'Otra')], default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='gameaccess',
            constraint=models.UniqueConstraint(fields=('library_entry', 'access_type', 'platform_name', 'store'), name='games_access_unique_location'),
        ),
        migrations.RemoveField(
            model_name='gameaccess',
            name='acquired_on',
        ),
        migrations.RemoveField(
            model_name='gameaccess',
            name='platform_family',
        ),
    ]
