# Generated by Django 6.0.7 on 2026-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gameaccess_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
