# Generated by Django 6.0.7 on 2026-07-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_genres_game_igdb_synced_at_game_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('dlc', 'DLC'), ('expansion', 'Expansion'), ('standalone_expansion', 'Standalone Expansion'), ('other', 'Other')], db_index=True, default='dlc', max_length=30)),
                ('status', models.CharField(choices=[('plan_to_play', 'Plan to Play'), ('playing', 'Playing'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='plan_to_play', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('first_release_date', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('igdb_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_contents', to='games.libraryentry')),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('library_entry', 'title'), name='games_content_unique_title'), models.CheckConstraint(condition=models.Q(('completed_on__isnull', True), ('status', 'completed'), _connector='OR'), name='games_content_completed_date_valid')],
            },
        ),
    ]
