# Generated by Django 6.0.7 on 2026-07-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_franchise_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playthrough',
            name='text_language',
            field=models.CharField(choices=[('unknown', 'Unspecified'), ('ja', 'Japanese'), ('en', 'English'), ('es', 'Spanish'), ('other', 'Other')], db_index=True, max_length=10),
        ),
    ]
