# Generated by Django 6.0.7 on 2026-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_playthrough_text_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccess',
            name='store',
            field=models.CharField(blank=True, choices=[('steam', 'Steam'), ('epic_games', 'Epic Games Store'), ('playstation_store', 'PlayStation Store'), ('nintendo_eshop', 'Nintendo eShop'), ('gog', 'GOG'), ('xbox', 'Xbox'), ('other', 'Otra')], default='', max_length=30),
        ),
    ]
