# Generated by Django 6.0.7 on 2026-07-25 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=16)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('overview', models.TextField(blank=True)),
                ('presentation', models.CharField(choices=[('animation', 'Animation / Cartoon'), ('live_action', 'Live Action'), ('documentary', 'Documentary'), ('mixed', 'Mixed'), ('other', 'Other')], default='live_action', max_length=24)),
                ('original_language', models.CharField(blank=True, max_length=16)),
                ('first_release_date', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('external_status', models.CharField(blank=True, max_length=64)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('origin_countries', models.JSONField(blank=True, default=list)),
                ('networks', models.JSONField(blank=True, default=list)),
                ('tmdb_payload', models.JSONField(blank=True, default=dict)),
                ('tmdb_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', False)), fields=('media_type', 'tmdb_id'), name='watchroom_unique_tmdb_identity'), models.CheckConstraint(condition=models.Q(('tmdb_id__isnull', True), ('tmdb_id__gt', 0), _connector='OR'), name='watchroom_tmdb_id_positive_or_null'), models.CheckConstraint(condition=models.Q(('runtime_minutes__isnull', True), ('runtime_minutes__gt', 0), _connector='OR'), name='watchroom_runtime_positive_or_null'), models.CheckConstraint(condition=models.Q(models.Q(('media_type', 'movie')), ('runtime_minutes__isnull', True), _connector='OR'), name='watchroom_series_runtime_is_null')],
            },
        ),
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('plan_to_watch', 'Plan to Watch'), ('watching', 'Watching'), ('paused', 'Paused'), ('dropped', 'Dropped'), ('completed', 'Completed')], db_index=True, default='plan_to_watch', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_entry', to='watchroom.mediawork')),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
            },
        ),
    ]
