# Generated by Django 6.0.7 on 2026-07-25 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('episode_count', models.PositiveIntegerField(default=0)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('tmdb_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='watchroom.mediawork')),
            ],
            options={
                'ordering': ('season_number', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('media_work', 'season_number'), name='watchroom_unique_season_number_per_work'), models.CheckConstraint(condition=models.Q(('tmdb_id__isnull', True), ('tmdb_id__gt', 0), _connector='OR'), name='watchroom_season_tmdb_id_positive_or_null')],
            },
        ),
    ]
