# Generated by Django 6.0.7 on 2026-07-25 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchroom', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, default='watching', max_length=16)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('progress_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watch_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_runs', to='watchroom.watchentry')),
            ],
            options={
                'ordering': ('number', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('watch_entry', 'number'), name='watchroom_unique_run_number_per_entry'), models.UniqueConstraint(condition=models.Q(('status__in', ('watching', 'paused'))), fields=('watch_entry',), name='watchroom_one_active_run_per_entry'), models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='watchroom_run_number_positive'), models.CheckConstraint(condition=models.Q(('started_on__isnull', True), ('finished_on__isnull', True), ('finished_on__gte', models.F('started_on')), _connector='OR'), name='watchroom_run_date_range_valid'), models.CheckConstraint(condition=models.Q(('progress_minutes__isnull', True), ('progress_minutes__gt', 0), _connector='OR'), name='watchroom_run_progress_positive_or_null')],
            },
        ),
    ]
