# Generated by Django 6.0.7 on 2026-07-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchroom', '0003_viewingrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_watched', models.PositiveIntegerField(default=0)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='watchroom.season')),
                ('viewing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_progress', to='watchroom.viewingrun')),
            ],
            options={
                'ordering': ('season__season_number', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('viewing_run', 'season'), name='watchroom_unique_season_progress_per_run'), models.CheckConstraint(condition=models.Q(('episodes_watched__gte', 0)), name='watchroom_episodes_watched_non_negative'), models.CheckConstraint(condition=models.Q(('started_on__isnull', True), ('finished_on__isnull', True), ('finished_on__gte', models.F('started_on')), _connector='OR'), name='watchroom_season_progress_date_range_valid')],
            },
        ),
    ]
