# Generated by Django 6.0.7 on 2026-07-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchroom', '0004_seasonprogress'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasonprogress',
            name='watchroom_season_progress_date_range_valid',
        ),
        migrations.RemoveField(
            model_name='seasonprogress',
            name='finished_on',
        ),
        migrations.RemoveField(
            model_name='seasonprogress',
            name='started_on',
        ),
    ]
