# Generated by Django 6.0.7 on 2026-07-26 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchroom', '0005_remove_seasonprogress_watchroom_season_progress_date_range_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('overview', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('tmdb_collection_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('tmdb_payload', models.JSONField(blank=True, default=dict)),
                ('tmdb_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FranchiseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(choices=[('main', 'Main'), ('spin_off', 'Spin-off'), ('special', 'Special'), ('extra', 'Extra'), ('other', 'Other')], default='main', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='watchroom.franchise')),
                ('media_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_memberships', to='watchroom.mediawork')),
            ],
            options={
                'ordering': ('franchise_id', 'position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='franchise',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='franchises', through='watchroom.FranchiseMembership', to='watchroom.mediawork'),
        ),
        migrations.AddConstraint(
            model_name='franchisemembership',
            constraint=models.UniqueConstraint(fields=('franchise', 'media_work'), name='watchroom_unique_franchise_work'),
        ),
        migrations.AddConstraint(
            model_name='franchisemembership',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='watchroom_franchise_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='franchise',
            constraint=models.CheckConstraint(condition=models.Q(('tmdb_collection_id__isnull', True), ('tmdb_collection_id__gt', 0), _connector='OR'), name='watchroom_franchise_tmdb_collection_positive_or_null'),
        ),
    ]
